### ISSUE TITLE
Implement 2-zone Ambilight

### ISSUE THREAD

**Issue by michaelrcarroll** [michaelrcarroll/script.kodi.hue.ambilight#12]
Original comment from @bredmich

Hi Michael,
i just tried to add the 2-Zone Ambilight Mode from acaranta to version 0.7.2 but it won´t work.
https://github.com/acaranta/script.xbmc.hue.ambilight/commit/89964823a663c09206ce7fc9d77db5dd2c0621de
https://github.com/acaranta/script.xbmc.hue.ambilight/commit/f76438720a99f130f9dd143518536b2a94eb9cd7

I get the following error:
20:19:35 T:4579803136   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndentationError'>
                                            Error Contents: ('expected an indented block', ('/Users/michaelbredehorn/Library/Application Support/Kodi/addons/script.kodi.hue.ambilight-master/default.py', 408, 17, '    spectrum_left = {}\n'))
                                            IndentationError: ('expected an indented block', ('/Users/michaelbredehorn/Library/Application Support/Kodi/addons/script.kodi.hue.ambilight-master/default.py', 408, 17, '    spectrum_left = {}\n'))
                                            -->End of Python script error report<--

Could you help me please ?

Thanks
Michael

**Comment by michaelrcarroll** [comment]
@bredmich, this is simply a code-formatting issue. python expects that a strict indentation convention is followed. check and see if you've used the right number of tabs/spaces for that code. if you do get this working, you should send a pull request and we can integrate it into the main release.

**Comment by bredmich** [comment]
Sorry for the comment, i'm new to github.
I'll try to get it working even though i'm not familiar with python.
Also i need to test the final setup, i just got one hue connected. I need to get two sockets to place them on the left and right of my tv.

Thanks !

**Comment by bredmich** [comment]
@michaelrcarroll I just solved the issue(s).
I will run a test with two Bulbs when I got the Sockets.

**Comment by bredmich** [comment]
Hi @michaelrcarroll,
i just created an own branch https://github.com/bredmich/script.kodi.hue.ambilight/tree/toPullRequest to implement the 2-Zone Ambilight mode.
1. Starting with Group 1 switched on and Light 2 + 3 switched on.
2. Starting Kodi
3. Light 2 + 3 will flash and dim to 50% as set in override_undim_bri
4. Starting any Movie and Group 1 will switched off and Light 2 + 3 will also dim from 50% to 0%
5. Kodi display that the Hue Plugin had an error.

```
21:17:47 T:4576026624  NOTICE: Kodi Hue: DEBUG state changed to: started
21:17:47 T:4576026624  NOTICE: Kodi Hue: DEBUG retrieving current setting before starting
21:17:47 T:4576026624  NOTICE: Kodi Hue: DEBUG capture 32 x 17
21:17:47 T:4576026624  NOTICE: Kodi Hue: DEBUG dimming group for ambilight
21:17:47 T:4576026624  NOTICE: Kodi Hue: DEBUG set_light2: group_id 1: {"transitiontime": 5, "on": false}
21:17:47 T:4576026624   ERROR: EXCEPTION Thrown (PythonToCppException):
-->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.UnboundLocalError'>
Error Contents: local variable 'h' referenced before assignment
Traceback (most recent call last):
File "/Users/michaelbredehorn/Library/Application Support/Kodi/addons/script.kodi.hue.ambilight-toPullRequest/default.py", line 641, in <module> run()
File "/Users/michaelbredehorn/Library/Application Support/Kodi/addons/script.kodi.hue.ambilight-toPullRequest/default.py", line 534, in run hsvRatios = screen.spectrum_hsv_zones(screen.pixels, screen.capture_width, screen.capture_height, 20)
File "/Users/michaelbredehorn/Library/Application Support/Kodi/addons/script.kodi.hue.ambilight-toPullRequest/default.py", line 451, in spectrum_hsv_zones if spectrum_left.has_key(h):
UnboundLocalError: local variable 'h' referenced before assignment
-->End of Python script error report<--
```

Then i tried to use the original Code from @acaranta and get the same error.
And it´s almost the same appearance as my implementation of this feature to your version.
1. Starting with Group 1 switched on and Light 2 + 3 switched on.
2. Starting Kodi
3. Light 2 + 3 will flash and dim to 50% as set in override_undim_bri
4. Starting any Movie and Light 2 + 3 will dim from 50% to 0%
5. But Group 1 stays on without any change
6. Kodi display that the Hue Plugin had an error.

```
21:41:56 T:4563419136  NOTICE: XBMC Hue: DEBUG state changed to: started
21:41:56 T:4563419136  NOTICE: XBMC Hue: DEBUG retrieving current setting before starting
21:41:57 T:4563419136  NOTICE: XBMC Hue: DEBUG capture 32 x 17
21:41:57 T:4563419136  NOTICE: XBMC Hue: DEBUG dimming lights
21:41:57 T:4563419136  NOTICE: XBMC Hue: DEBUG class Hue: dim lights
21:41:57 T:4563419136  NOTICE: XBMC Hue: DEBUG set_light: 2: {"on":true,"bri":0,"transitiontime":5}
21:41:57 T:140735255487232 WARNING: CRenderCaptureGL: GL_ARB_occlusion_query disabled, performance might suffer
21:41:57 T:4563419136  NOTICE: XBMC Hue: DEBUG set_light: 2: {"on":false}
21:41:57 T:4563419136  NOTICE: XBMC Hue: DEBUG set_light: 3: {"on":true,"bri":0,"transitiontime":5}
21:41:57 T:4563419136  NOTICE: XBMC Hue: DEBUG set_light: 3: {"on":false}
21:41:57 T:4563419136   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.UnboundLocalError'>
Error Contents: local variable 'h' referenced before assignment
Traceback (most recent call last):
File "/Users/michaelbredehorn/Library/Application Support/Kodi/addons/script.xbmc.hue.ambilight-f76438720a99f130f9dd143518536b2a94eb9cd7/default.py", line 570, in <module> run()
File "/Users/michaelbredehorn/Library/Application Support/Kodi/addons/script.xbmc.hue.ambilight-f76438720a99f130f9dd143518536b2a94eb9cd7/default.py", line 483, in run hsvRatios = screen.spectrum_hsv_zones(screen.pixels, screen.capture_width, screen.capture_height, 20)
File "/Users/michaelbredehorn/Library/Application Support/Kodi/addons/script.xbmc.hue.ambilight-f76438720a99f130f9dd143518536b2a94eb9cd7/default.py", line 400, in spectrum_hsv_zones if spectrum_left.has_key(h):
UnboundLocalError: local variable 'h' referenced before assignment
-->End of Python script error report<--
```

I´m not sure about the Capture warning, as we got some code about capturing ...
```
21:41:57 T:140735255487232 WARNING: CRenderCaptureGL: GL_ARB_occlusion_query disabled, performance might suffer
```

If i use mode 0 = Ambilight (normal) everything works just fine.
So the problem have to be part of the code from @acaranta ...

Maybe you could look into this if you got time.
I´m focusing on some other parts of this addon.

Cheers
Michael

**Comment by acaranta** [comment]
Woops ... err ... I should probably have dropped my branch, because as far as I remember my code truly didn't work ;) 

I actually had that idea but the result was a/ not working b/ the machine where I tested the extension was way too slow for any of this to work ;)

Sorry if I gave false hopes on a proper working code :(

**Comment by michaelrcarroll** [comment]
ah, no worries. I had started working on it myself, but it seems there are bigger issues with the single-zone ambilight that need to be resolved before making it more complex. I still want to tackle this a bit later...
