### ISSUE TITLE
Choose between group and single bulb dim

### ISSUE THREAD

**Issue by bredmich** [michaelrcarroll/script.kodi.hue.ambilight#13]
I´m using the feature to dim a group of lights when the playback starts.
As mentioned in the settings the group only react really slow or just stay in the last state.
I only need the addon to dim one light because it´s a Living Whites Adapter for all my LEDs behind the TV rack.
Now i got one group with only one light, it´s not really fast and sometimes takes up to 1 minute to change the state from dimmed to undimmed.

Is it possible to add the option to switch between a group of lights to dim or only one light to dim ?
Or just add another Switch for this Option.

**Comment by bredmich** [comment]
I already started to add this feature in the settings.
https://github.com/bredmich/script.kodi.hue.ambilight/commit/5700704e2da04fd5eff429abc248f0deaa1d425b

But i´m not able to add the function itself.
I´m not familiar enough with python, hue and kodi addons to do this.

**Comment by michaelrcarroll** [comment]
Good stuff, I see what you've started. Group mode *is* too slow to be used for the ambilight. Philips actually only recommends that you use group mode with 12 or more lights, so I'll probably be changing the light input to be a comma separated list of lights instead. But I agree that the single light mode for ambilight is important. I'll look into this for 0.8.

**Comment by bredmich** [comment]
At the moment the dim group mode isn´t working at all.
There is no error in the kodi.log
```
22:15:24 T:4567126016  NOTICE: Kodi Hue: DEBUG state changed to: started
22:15:24 T:4567126016  NOTICE: Kodi Hue: DEBUG retrieving current setting before starting
22:15:24 T:4567126016  NOTICE: Kodi Hue: DEBUG dimming lights
22:15:24 T:4567126016  NOTICE: Kodi Hue: DEBUG class Hue: dim lights
22:15:24 T:4567126016  NOTICE: Kodi Hue: DEBUG set_light2: 2: {"transitiontime": 5, "hue": 34867, "on": false}
22:15:24 T:4567126016  NOTICE: Kodi Hue: DEBUG set_light2: 3: {"transitiontime": 5, "hue": 34867, "on": false}
22:15:38 T:4567126016  NOTICE: Kodi Hue: DEBUG state changed to: paused
22:15:38 T:4567126016  NOTICE: Kodi Hue: DEBUG class Hue: partial lights
22:15:38 T:4567126016  NOTICE: Kodi Hue: DEBUG set_light2: 2: {"transitiontime": 5, "hue": 34867, "on": true, "bri": 76, "sat": 144}
22:15:39 T:4567126016  NOTICE: Kodi Hue: DEBUG set_light2: 3: {"transitiontime": 5, "hue": 34867, "on": true, "bri": 76, "sat": 0}
```

It´s not important if the LivingWhites (Group 1) is on before the start of kodi or not.
It seems like kodi isn´t trying to change the state for Group 1 when starting, pausing or ending a playback.

**Comment by bredmich** [comment]
Okay i found the problem for me.
The function for dimming the group only gets active if hue.settings.mode is 0.
```python
    if hue.settings.mode == 0 and hue.settings.ambilight_dim:
```
If we want to get the 2-Zone Ambilight feature to work with ambilight_dim, we have to change this.

Maybe something like:
```python
    if (hue.settings.mode == 0 or hue.settings.mode == 2) and hue.settings.ambilight_dim:
```

Cheers
Michael

**Comment by bredmich** [comment]
The function wasn´t working because of the 2-Zone Ambilight mode. The mode messed everything up and nothing worked as planned.

Now i tested the feature in the normal Ambilight mode and it *works* ...
Sometimes it takes up to 30 seconds to change the groupe state from off to on and vice versa.

Maybe i´ll find some time this weekend to look into it ...

**Comment by bredmich** [comment]
I tried your develop branch and get this error when starting kodi:
```
13:29:57 T:4574978048  NOTICE: Kodi Hue service started, version: 0.8
13:29:57 T:4574978048   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.ValueError'>
Error Contents: invalid literal for int() with base 10: ''
Traceback (most recent call last):
File "/Users/michaelbredehorn/Library/Application Support/Kodi/addons/script.kodi.hue.ambilight-develop/default.py", line 650, in <module> settings = settings()
File "/Users/michaelbredehorn/Library/Application Support/Kodi/addons/script.kodi.hue.ambilight-develop/resources/lib/settings.py", line 8, in __init__ self.readxml()
File "/Users/michaelbredehorn/Library/Application Support/Kodi/addons/script.kodi.hue.ambilight-develop/resources/lib/settings.py", line 46, in readxml self.ambilight_dim_group   = int(__addon__.getSetting("ambilight_dim_group")) #CLEANUP: Not needed anymore
ValueError: invalid literal for int() with base 10: ''
-->End of Python script error report<--
```

**Comment by michaelrcarroll** [comment]
@bredmich Yep, hadn't cleaned up that setting yet (```develop``` isn't the most stable of branches just yet), but did a lot of stuff today that should make it better.

That setting has been removed and the force lights on setting now works (because i was being an idiot before). See https://github.com/michaelrcarroll/script.kodi.hue.ambilight/commit/e386ea30fb7e0d3bcade896b61f2b235dca1adfc

I'm pretty sure the pre/post ambilight dimming is looking good. Going to tackle two-zone next.

**Comment by bredmich** [comment]
Yeah, i´m aware of this.
I like to test things out, even if it´s in developement.

I´ll test it out today and give you an feedback.

Cheers
Michael

**Comment by bredmich** [comment]
Ok i just finished my test.

1. Starting Kodi
2. *light1_id* and *light2_id* get dimmed from 0% to 50% as planned.
3. *dim_light1_id* stays at 0%.
4. Starting a playback and *light1_id* and *light2_id* doing their job between 5% and 60% as planned.
5. Pausing the playback, *light1_id* and *light2_id* get dimmed to 30% as planned. But *dim_light1_id* do nothing.
6. Stopping the playback, *light1_id* and *light2_id* get dimmed to 50% as planned. *dim_light1_id* get turned on.

The Ambilight Mode is working smoothly and looks great !
*Just waiting for the 2-Zone Mode to get it even better*

The Dimming Function works, but isn´t perfect for my opinion.
The light doesn´t get turned on with the others on startup.
The light doesn´t get turned on while pausing a playback.

Just for your information, my current setup contains:
1. Philips Ambilight TV
2. 2 x Philips Hue E27 Bulbs in milk glass spckets.
3. 1 x Philips Living Whites Adapter to controll the LEDs in my TV Rack.
*The Living Whites is only set to on/off because i need to find a new AC Adapter thats able to dim correctly*

The Living Whites is only off when the brightness is 0, every value between 1 and 100 will turn it on.


Cheers
Michael
