### ISSUE TITLE
Crash on Kodi 15.1

### ISSUE THREAD

**Issue by michaelrcarroll** [michaelrcarroll/script.kodi.hue.ambilight#2]
Kodi 15.1 on an Android box (I have only tested on 14.2 (hurry up and release your update, OpenELEC!)

Should easily be fixable.

```
19:25:11 T:1915786992  NOTICE: Kodi Hue service started, version: 0.7.1
19:25:11 T:1915786992   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: list indices must be integers, not str
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/default.py", line 498, in <module>
                                                hue = Hue(settings, args)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/default.py", line 96, in __init__
                                                self.update_settings()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/default.py", line 203, in update_settings
                                                self.light = Group(self.settings)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/resources/lib/tools.py", line 236, in __init__
                                                Light.__init__(self, settings.light1_id, settings)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/resources/lib/tools.py", line 105, in __init__
                                                self.get_current_setting()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/resources/lib/tools.py", line 121, in get_current_setting
                                                state = j['state']
                                            TypeError: list indices must be integers, not str
                                            -->End of Python script error report<--
19:25:24 T:1786024544 WARNING: RunScript called for a non-script addon 'script.kodi.hue.ambilight'. This behaviour is deprecated.
19:25:24 T:1937980520  NOTICE: Thread LanguageInvoker start, auto delete: false
19:25:24 T:1937980520  NOTICE: -->Python Interpreter Initialized<--
19:25:25 T:1937980520  NOTICE: Kodi Hue service started, version: 0.7.1
19:25:25 T:1937980520   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: list indices must be integers, not str
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/default.py", line 498, in <module>
                                                hue = Hue(settings, args)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/default.py", line 96, in __init__
                                                self.update_settings()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/default.py", line 203, in update_settings
                                                self.light = Group(self.settings)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/resources/lib/tools.py", line 236, in __init__
                                                Light.__init__(self, settings.light1_id, settings)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/resources/lib/tools.py", line 105, in __init__
                                                self.get_current_setting()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/resources/lib/tools.py", line 121, in get_current_setting
                                                state = j['state']
                                            TypeError: list indices must be integers, not str
                                            -->End of Python script error report<--
19:25:26 T:1786024544 WARNING: RunScript called for a non-script addon 'script.kodi.hue.ambilight'. This behaviour is deprecated.
19:25:26 T:1954557480  NOTICE: Thread LanguageInvoker start, auto delete: false
19:25:26 T:1954557480  NOTICE: -->Python Interpreter Initialized<--
19:25:27 T:1954557480  NOTICE: Kodi Hue service started, version: 0.7.1
19:25:27 T:1954557480   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: list indices must be integers, not str
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/default.py", line 498, in <module>
                                                hue = Hue(settings, args)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/default.py", line 96, in __init__
                                                self.update_settings()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/default.py", line 203, in update_settings
                                                self.light = Group(self.settings)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/resources/lib/tools.py", line 236, in __init__
                                                Light.__init__(self, settings.light1_id, settings)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/resources/lib/tools.py", line 105, in __init__
                                                self.get_current_setting()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/resources/lib/tools.py", line 121, in get_current_setting
                                                state = j['state']
                                            TypeError: list indices must be integers, not str
                                            -->End of Python script error report<--
19:25:41 T:1786024544 WARNING: RunScript called for a non-script addon 'script.kodi.hue.ambilight'. This behaviour is deprecated.
19:25:41 T:1945734808  NOTICE: Thread LanguageInvoker start, auto delete: false
19:25:41 T:1945734808  NOTICE: -->Python Interpreter Initialized<--
19:25:41 T:1945734808  NOTICE: Kodi Hue service started, version: 0.7.1
19:25:41 T:1945734808   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: list indices must be integers, not str
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/default.py", line 498, in <module>
                                                hue = Hue(settings, args)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/default.py", line 96, in __init__
                                                self.update_settings()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/default.py", line 203, in update_settings
                                                self.light = Group(self.settings)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/resources/lib/tools.py", line 236, in __init__
                                                Light.__init__(self, settings.light1_id, settings)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/resources/lib/tools.py", line 105, in __init__
                                                self.get_current_setting()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/resources/lib/tools.py", line 121, in get_current_setting
                                                state = j['state']
                                            TypeError: list indices must be integers, not str
                                            -->End of Python script error report<--
19:25:43 T:1786024544 WARNING: RunScript called for a non-script addon 'script.kodi.hue.ambilight'. This behaviour is deprecated.
19:25:43 T:1948814456  NOTICE: Thread LanguageInvoker start, auto delete: false
19:25:43 T:1948814456  NOTICE: -->Python Interpreter Initialized<--
19:25:43 T:1948814456  NOTICE: Kodi Hue service started, version: 0.7.1
19:25:43 T:1948814456   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: list indices must be integers, not str
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/default.py", line 498, in <module>
                                                hue = Hue(settings, args)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/default.py", line 96, in __init__
                                                self.update_settings()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/default.py", line 203, in update_settings
                                                self.light = Group(self.settings)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/resources/lib/tools.py", line 236, in __init__
                                                Light.__init__(self, settings.light1_id, settings)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/resources/lib/tools.py", line 105, in __init__
                                                self.get_current_setting()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.hue.ambilight-master/resources/lib/tools.py", line 121, in get_current_setting
                                                state = j['state']
                                            TypeError: list indices must be integers, not str
                                            -->End of Python script error report<--
19:27:36 T:1948814456  NOTICE: Thread JobWorker start, auto delete: true
19:27:49 T:1914718144  NOTICE: Thread BackgroundLoader start, auto delete: false
19:27:50 T:1937515128  NOTICE: Thread JobWorker start, auto delete: true
```

**Comment by michaelrcarroll** [comment]
Issue was reported as resolved by user. Re-pairing with bridge fixed issue.
