### ISSUE TITLE
Kodi v17 

### ISSUE THREAD

**Issue by tdhz77** [michaelrcarroll/script.kodi.hue.ambilight#47]
22:07:57 T:140522790311680   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.ConnectionError'>
                                            Error Contents: HTTPConnectionPool(host='192.168.1.222', port=80): Max retries exceeded with url: /api/47af19f845120176643b1c7f2a6065a1/$
                                            Traceback (most recent call last):
                                              File "/home/hg/.kodi/addons/script.kodi.hue.ambilight-0.8b2/default.py", line 760, in <module>
                                                hue = Hue(settings, args)
                                              File "/home/hg/.kodi/addons/script.kodi.hue.ambilight-0.8b2/default.py", line 174, in __init__
                                                result = self.test_connection()
                                              File "/home/hg/.kodi/addons/script.kodi.hue.ambilight-0.8b2/default.py", line 297, in test_connection
                                                (self.settings.bridge_ip, self.settings.bridge_user))
                                              File "/home/hg/.kodi/addons/script.module.requests/lib/requests/api.py", line 67, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/home/hg/.kodi/addons/script.module.requests/lib/requests/api.py", line 53, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/home/hg/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 468, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "/home/hg/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 576, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/home/hg/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 437, in send
                                                raise ConnectionError(e, request=request)
         ConnectionError: HTTPConnectionPool(host='192.168.1.222', port=80): Max retries exceeded with url: /api/47af19f845120176643b1c7f2a6065a1$
                                            -->End of Python script error report<--

**Comment by tdhz77** [comment]
Interesting enough if I hit pause and play. The lights work as expected...

**Comment by tdhz77** [comment]
... this is hit or miss. Can't really figure out why it will work one minute and not the next.

**Comment by compuw22c** [comment]
I'm also seeing issues with v17.  Which is a shame, because WavForHue my other favorite add-on won't work with Jarvis but will work with v17 :P
