### ISSUE TITLE
Automatic configuration is not working

### ISSUE THREAD

**Issue by sethhere04** [michaelrcarroll/script.kodi.hue.ambilight#5]
Hi,
I cant get the automatic configuration to work. Even if i put in the ip address and Id from meethue.com it still says it cant connect. any help would be appreciated!

**Comment by michaelrcarroll** [comment]
Can you please check the version of your bridge? This can be found under the Hue app -> Settings -> About and looks like ```01028090``` (that is my version number).

I believe this may be due to a change in the way that the Hue's auto-pairing mode works with the latest update: http://www.developers.meethue.com/documentation/changes-bridge-discovery

**Comment by sethhere04** [comment]
That is the same version of the bridge I have.

**Comment by sethhere04** [comment]
i updated to the .8 develop version and still cant get it to connect. any help would be appreciated

**Comment by michaelrcarroll** [comment]
There have been no changes to the auto-configuration code in the ```develop``` branch. I have tested this with my bridge (which we confirmed to be the same version), and I was able to successfully autodiscover it. You should not need to use any information from meethue.com, the bridge configuration is all on your local network. The "Click me for automatic configuration" should find your bridge (as long as it is on the same network as your Kodi installation), and then initiate a countdown for you to physically press the button on the bridge to confirm the pairing.

Please let me know if this is the same auto-configuration that you are trying, and we can see if there is anything else that could be the issue.

**Comment by sethhere04** [comment]
When I click on the auto configuration option the popup comes up and then goes away and nothing happens. A few minutes later I get the error message to check the logs.

**Comment by digitalf** [comment]
Hi, 
I have exactly the same problem with the connect-procedure. The addon worked fine until I received an update for my bridge; now I get an error at every startup and the autoconfiguration ends in the same error.
I run Kodi 15.2 RC3 under  Windows10.

Best regards from the worldfamous black forest
Frank
PS: These are the results of the logfile:

13:25:52 T:652  NOTICE: Starting Kodi (15.2-RC3 Git:20151004-cf72616). Platform: Windows NT x86 32-bit
13:25:52 T:652  NOTICE: Using Release Kodi x32 build
13:25:52 T:652  NOTICE: Kodi compiled Oct  4 2015 by MSVC 180030723 for Windows NT x86 32-bit version 6.0 (0x06000000)
13:25:52 T:652  NOTICE: Running on Acer Aspire 7750G with Windows 10, kernel: Windows NT x86 64-bit version 10.0
13:25:52 T:652  NOTICE: Host CPU: Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz, 8 cores available
13:25:52 T:652  NOTICE: Desktop Resolution: 1920x1080 32Bit at 60Hz
13:25:52 T:652  NOTICE: Running with restricted rights
13:25:52 T:652  NOTICE: Aero is enabled
...
...
13:26:29 T:652 WARNING: RunScript called for a non-script addon 'script.kodi.hue.ambilight'. This behaviour is deprecated.
...
...
13:27:29 T:3544   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'socket.timeout'>
                                            Error Contents: timed out
                                            Traceback (most recent call last):
                                              File "C:\Users\Frank\AppData\Roaming\Kodi\addons\script.kodi.hue.ambilight-master\default.py", line 498, in <module>
                                                hue = Hue(settings, args)
                                              File "C:\Users\Frank\AppData\Roaming\Kodi\addons\script.kodi.hue.ambilight-master\default.py", line 104, in __init__
                                                hue_ip = start_autodisover()
                                              File "C:\Users\Frank\AppData\Roaming\Kodi\addons\script.kodi.hue.ambilight-master\resources\lib\tools.py", line 55, in start_autodisover
                                                recv_data, addr = client_socket.recvfrom(2048)
                                            timeout: timed out

**Comment by michaelrcarroll** [comment]
@digitalf Thanks for posting the log. That really helps narrow the issue down. I'll be looking into this some more (and adding some more logging to see what's going on under the hood and should have a special update for you guys to try out.

**Comment by sethhere04** [comment]
Great thanks! I am using Windows 8.1 and kodi 15.2 also. Just so you are aware.

**Comment by michaelrcarroll** [comment]
@sethhere04 @digitalf Hey! [0.7.2](https://github.com/michaelrcarroll/script.kodi.hue.ambilight/releases/tag/0.7.2) was just posted. You should give it a shot as it's got some more logging and fixes that may help me further debug your issues.

Please follow the instructions in the [Debugging](https://github.com/michaelrcarroll/script.kodi.hue.ambilight#debugging) section of the readme to record and submit log files of what happens.

**Comment by digitalf** [comment]
Hi Michael,

thx for your fast response. I've posted the Logfile under 
http://xbmclogs.com/puy7nc536

Kind regards from the  world famous Black Forest

Frank

**Comment by fluffypony** [comment]
This is reproducible by me. I'm running the develop branch on Kodi 15.2, but perhaps of note is that I'm using the new Hue bridge (the square one that adds Apple HomeKit support).

```
13:39:50 T:8560   DEBUG: ------ Window Init (DialogAddonSettings.xml) ------
13:39:50 T:8560   DEBUG: LocalizeStrings: no strings.po file exist at C:\Users\ric_000\AppData\Roaming\Kodi\addons\script.kodi.hue.ambilight-develop\resources\language\English, fallback to strings.xml
13:39:52 T:8560   DEBUG: CInputManager::ProcessMouse: trying mouse action leftclick
13:39:52 T:8560 WARNING: RunScript called for a non-script addon 'script.kodi.hue.ambilight'. This behaviour is deprecated.
13:39:52 T:3648  NOTICE: Thread LanguageInvoker start, auto delete: false
13:39:52 T:3648    INFO: initializing python engine.
13:39:52 T:3648   DEBUG: CPythonInvoker(10, C:\Users\ric_000\AppData\Roaming\Kodi\addons\script.kodi.hue.ambilight-develop\default.py): start processing
13:39:52 T:3648  NOTICE: -->Python Interpreter Initialized<--
13:39:52 T:3648   DEBUG: CPythonInvoker(10, C:\Users\ric_000\AppData\Roaming\Kodi\addons\script.kodi.hue.ambilight-develop\default.py): the source file to load is "C:\Users\ric_000\AppData\Roaming\Kodi\addons\script.kodi.hue.ambilight-develop\default.py"
13:39:52 T:3648   DEBUG: CPythonInvoker(10, C:\Users\ric_000\AppData\Roaming\Kodi\addons\script.kodi.hue.ambilight-develop\default.py): setting the Python path to C:\Users\ric_000\AppData\Roaming\Kodi\addons\script.kodi.hue.ambilight-develop;C:\Users\ric_000\AppData\Roaming\Kodi\addons\script.module.requests\lib;C:\Program Files (x86)\Kodi\system\python\DLLs;C:\Program Files (x86)\Kodi\system\python\Lib;C:\Program Files (x86)\Kodi\python27.zip;C:\Program Files (x86)\Kodi\system\python\lib\plat-win;C:\Program Files (x86)\Kodi\system\python\lib\lib-tk;C:\Program Files (x86)\Kodi;C:\Program Files (x86)\Kodi\system\python;C:\Program Files (x86)\Kodi\system\python\lib\site-packages
13:39:52 T:3648   DEBUG: CPythonInvoker(10, C:\Users\ric_000\AppData\Roaming\Kodi\addons\script.kodi.hue.ambilight-develop\default.py): entering source directory C:\Users\ric_000\AppData\Roaming\Kodi\addons\script.kodi.hue.ambilight-develop
13:39:52 T:3648   DEBUG: CPythonInvoker(10, C:\Users\ric_000\AppData\Roaming\Kodi\addons\script.kodi.hue.ambilight-develop\default.py): instantiating addon using automatically obtained id of "script.kodi.hue.ambilight" dependent on version 2.1.0 of the xbmc.python api
13:39:52 T:3648  NOTICE: Kodi Hue service started, version: 0.8
13:39:52 T:8560   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
13:39:54 T:8560   DEBUG: ------ Window Deinit (DialogKaiToast.xml) ------
13:39:57 T:8560   DEBUG: ------ Window Deinit (Pointer.xml) ------
13:40:02 T:3648   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
											 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
											Error Type: <class 'socket.timeout'>
											Error Contents: timed out
											Traceback (most recent call last):
											  File "C:\Users\ric_000\AppData\Roaming\Kodi\addons\script.kodi.hue.ambilight-develop\default.py", line 618, in <module>
												hue = Hue(settings, args)
											  File "C:\Users\ric_000\AppData\Roaming\Kodi\addons\script.kodi.hue.ambilight-develop\default.py", line 157, in __init__
												hue_ip = self.start_autodiscover()
											  File "C:\Users\ric_000\AppData\Roaming\Kodi\addons\script.kodi.hue.ambilight-develop\default.py", line 194, in start_autodiscover
												recv_data, addr = client_socket.recvfrom(2048)
											timeout: timed out
											-->End of Python script error report<--
13:40:02 T:8560   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
13:40:02 T:3648    INFO: Python script stopped
13:40:02 T:3648   DEBUG: Thread LanguageInvoker 3648 terminating
13:40:04 T:8560   DEBUG: Keyboard: scancode: 0x01, sym: 0x001b, unicode: 0x001b, modifier: 0x0
13:40:04 T:8560   DEBUG: CInputManager::OnKey: escape (0xf01b) pressed, action is PreviousMenu
13:40:04 T:8560   DEBUG: ------ Window Deinit (DialogAddonSettings.xml) ------
```

Manually setting the IP will probably work, but the autodiscover system probably just needs to use ```socket.socket()``` in a non-blocking manner and handle ```socket.timeout``` errors (I guess:)

**Comment by michaelrcarroll** [comment]
I think we still want non-blocking mode, but I have added a a catch block for this exception so it will continue on to try the nupnp discovery method (see https://github.com/michaelrcarroll/script.kodi.hue.ambilight/commit/6ed2d12cc5b8fa5033d15162e8082173e6d2f361). This will be rolled into v0.8 once i address some of the ambilight issues.

**Comment by bredmich** [comment]
I just discovered something about the automatic configuration.
If you already set up a user (xbmc-player/kodi-player) you´re not able to create another user with that name in the bridge.

I don´t know if the bridge is giving this information when trying to register the same user.
And it seems like there is no way to check all existing users in the bridge.

Just for your information.

Another way for users with more Know-How is to setup the user manually.
Maybe you could add this to the FAQ, just tell me if you want to share some work.

Cheers
Michael

**Comment by fluffypony** [comment]
OH - does this try create a named user? Those are being deprecated from the Hue API, you have to use the one randomly generated by the bridge. That functionality will disappear entirely from Feb 2016.

Reference: http://www.developers.meethue.com/documentation/important-whitelist-changes

**Comment by bredmich** [comment]
```python
def register_user(hue_ip):
  username = hashlib.md5(str(random.random())).hexdigest()
  device = "kodi-player"
  data = '{"username": "%s", "devicetype": "%s"}' % (username, device)
```
Thats the function to register a new user, i´m not user if it´s still used.

**Comment by michaelrcarroll** [comment]
@fluffypony @bredmich you're absolutely right. although we supply a username parameter, it is ignored and we use the randomly-generated hash username. I've opened up a new issue (#16) to track this.

Re: the devicetype uniqueness: I have multiple kodi installations with this addon running on my home network and they are all able to successfully pair with the bridge (using the same devicetype). Are you having an error with this? I have noticed that if you have a bridge IP and/or username set that autoconfiguration will fail (clearing to "" works). See #17.

**Comment by slicslic** [comment]
hello michael and thanx for your work.

i tried your addon for kodi 15.2 on windows 7 computer and i already have this error message 

07:07:05 T:6836   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!

with your new build 6ed2d12 (v8.0) i have some new more details

Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: Light instance has no attribute 'group_id'
notify("Group Not Found", "Could not find group %s in bridge." % self.group_id)
                                            AttributeError: Light instance has no attribute 'group_id'

thanx in advance for your help and sorry for my english

**Comment by Ashe80** [comment]
Hello,

I have similar problem that my Hue is not detected any more by the addon.
I am observing this thread for a while already.

Is there any update available?

**Comment by Ashe80** [comment]
Hey, thx for the beta 0.8 1 update.

Now auto-discovery is working fine.
One issue i have:
If i set mode to Theatre it have always like ambilight setting.
Ambilight behave the same - like ambilight.

But we are one step further :-)
Have a nice holiday

**Comment by michaelrcarroll** [comment]
@Ashe80 Might want to nuke your ```userdata/addon_data/script.kodi.hue.ambilight/settings.xml``` file and set up the add-on again (you can find the userdata folder from the locations listed at http://kodi.wiki/view/Userdata). There were changes to the add-on's settings structure that may have caused the mode to not be detected properly.

**Comment by Ashe80** [comment]
Thx for the fast hint. After deleting the file and resetup, it is working fine 😉
Happy holidays

**Comment by sethhere04** [comment]
Auto discovery is now working. But ambilight is not controlling lights.

**Comment by johnworkgit** [comment]
with v8.1 beta auto-discovery works for me, but I have to redo the auto discovery every time i start kodi else nothing will happen with the lights. No configuration is lost (ip, username) as when i open the kodi hue config (after restarting kodi) there's nothing missing. I have the newer squared bridge. I was using the stable version that worked perfectly before, but after a update on the bridge i can only auto discover with v.8.1

**Comment by michaelrcarroll** [comment]
0.8b2 has been posted. This should fix the issues @johnworkgit and @sethhere04 posted. ambilight should work on first launch now that the settings are reloaded once the connection is tested. Similarly, the not iterable error was due to the lights not being enumerated from the bridge (which is now triggered).

**Comment by sethhere04** [comment]
Fixed all of my issues. Works great now! Thanks.

**Comment by epacheco13** [comment]
I am having issues using automatic configuration. I keep receiving a message saying that it cannot find my bridge. I have enabled debugging and looked in the logs, I have attached them for you. I am running kodi on openelec version 6.0.3.

Thanks!

<img width="629" alt="screen shot 2016-03-11 at 12 29 18 pm" src="https://cloud.githubusercontent.com/assets/17787431/13710119/89fb5800-e785-11e5-9fa0-06d29e5ebb85.png">
