### ISSUE TITLE
Error when trying to auto configure bridge

### ISSUE THREAD

**Issue by Bully268** [michaelrcarroll/script.kodi.hue.ambilight#53]
After clicking the option to auto configure the bridge I get a script error.
As can be seen in these logs:
http://xbmclogs.com/pvj3rtnqv

**Comment by bouvin** [comment]
I, too, get an error at the same point:

23:30:06 T:139902409586752 WARNING: RunScript called for a non-script addon 'script.kodi.hue.ambilight'. This behaviour is deprecated.
23:30:06 T:139899952944896  NOTICE: Kodi Hue service started, version: 0.7.2
23:30:08 T:139899952944896   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: list indices must be integers, not str
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.kodi.hue.ambilight-master/default.py", line 533, in <module>
                                                hue = Hue(settings, args)
                                              File "/storage/.kodi/addons/script.kodi.hue.ambilight-master/default.py", line 113, in __init__
                                                self.update_settings()
                                              File "/storage/.kodi/addons/script.kodi.hue.ambilight-master/default.py", line 248, in update_settings
                                                self.light[0] = Light(self.settings.light1_id, self.settings)
                                              File "/storage/.kodi/addons/script.kodi.hue.ambilight-master/resources/lib/tools.py", line 81, in __init__
                                                self.get_current_setting()
                                              File "/storage/.kodi/addons/script.kodi.hue.ambilight-master/resources/lib/tools.py", line 97, in get_current_setting
                                                state = j['state']
                                            TypeError: list indices must be integers, not str
                                            -->End of Python script error report<--

**Comment by bouvin** [comment]
Looking further, this is what is contained in the ‘j’ list:
[{u'error': {u'type': 1, u'description': u'unauthorized user', u'address': u'/lights'}}]
So, clearly something goes awry upon connection to the bridge.

**Comment by kapps7** [comment]
I have the same error. Could it be a compatibility issue with the new firmware for the hue bridge ?

**Comment by maho2nd** [comment]
There seems to be an authorization problem (with the new bridge?). To get access to the bridge you need to acquire a username and then press the bridge button. This doesn't happend.

I solved it by manually create a user and modified the settings file. Here step by step:

1) Open following address in your browser http://<YOUR_BRIDGE_UP>/debug/clip.html

2) In the formular, set the url to `/api/` and the Message Body to `{"devicetype":"my_hue_app#openelec"}`

3) Click on POST button and then press the bridge button

4) Click again on POST button. Then you should see a response with a user name.

5) Access your kodi device and edit /storage/.kodi/userdata/addon_data/script.kodi.hue.ambilight/settings.xml

6) Change the value bridge_user to the new one.

7) Restart kodi

**Comment by hollyjack1975** [comment]
maho2nd I have read you comment above. I have kodi on a Amazon fire box can I do what you are saying on my setup?

**Comment by maho2nd** [comment]
I don't know the fire box, but if you have access to the filesystem/be able to edit files, it should be possible.

**Comment by hollyjack1975** [comment]
Do I access this on kodi it self?

**Comment by maho2nd** [comment]
No, not without a text editor plugin. Maybe this can help you: https://superrepo.org/de/kodi/addon/plugin.devtool.texteditor/

Another way is per ssh. But I think the best is to ask someone how know the firebox internals.

**Comment by hollyjack1975** [comment]
Thanks very much for your help . I got the text editor and to be honest now I'm even more confused. I appreciate your help. I am gutted I'm not clever enough to fix it.... if you hear of a quick fix in the future please can you update me?

Thanks again!

**Comment by hollyjack1975** [comment]
I have a raspberry Pi can I do it on that?

**Comment by maho2nd** [comment]
Yes!

How did you installed kodi on your raspberry? If used openelect, try following:

1. Enable ssh server on your raspberry. You can activate ssh in the openelect settings under services.

2. Establish a ssh connection to your raspberry. If you're using windows, you can use http://www.putty.org/ as a ssh client. If you're using linux it afaik already installed. 

3. Go on your kodi directory (in my case I enter `cd /storage/.kodi/`)

4. Edit the settings file `vi userdata/addon_data/script.kodi.hue.ambilight/settings.xml`

5. Change the value of bridge_user to the new one (as I described in an older post) and save the file.

If you installed kodi manually, than this may be the easiest way:

1. Connect a keyboard and monitor to your raspberry and boot it with GUI (startx)

2. Edit the file `userdata/addon_data/script.kodi.hue.ambilight/settings.xml` in your kodi installation folder

3. Change the value of bridge_user to the new one (as I described in an older post)

**Comment by hollyjack1975** [comment]
Wow thanks for the info ! I am using kodi on my raspberry pi through open elec. I am better good with computers but this is voodoo to my can you talk my through it via Skype? I'd be happy to pay for your time?

**Comment by maho2nd** [comment]
My skype name is maho15.

**Comment by hollyjack1975** [comment]
Fantastic is tomorrow any good? I am in the U.K.
But happy to do it and your  convenience .

I have a mac what program do I need installed?

**Comment by maho2nd** [comment]
Let's resume in skype to don't spam this ticket any more ;)
