### ISSUE TITLE
Automatic configuration is not working (2016-05-28)

### ISSUE THREAD

**Issue by manuel-kuehner** [michaelrcarroll/script.kodi.hue.ambilight#59]
Hello, I just wanted to use yout addon and I experience an error. My bridge is not connected - this is what the log file says:

```
12:31:57 T:8836 WARNING: RunScript called for a non-script addon 'script.kodi.hue.ambilight'. This behaviour is deprecated.
12:31:57 T:8  NOTICE: Kodi Hue service started, version: 0.7.2
12:32:07 T:8   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'socket.timeout'>
                                            Error Contents: timed out
                                            Traceback (most recent call last):
                                              File "C:\Users\manu\AppData\Roaming\Kodi\addons\script.kodi.hue.ambilight-master\default.py", line 533, in <module>
                                                hue = Hue(settings, args)
                                              File "C:\Users\manu\AppData\Roaming\Kodi\addons\script.kodi.hue.ambilight-master\default.py", line 104, in __init__
                                                hue_ip = self.start_autodiscover()
                                              File "C:\Users\manu\AppData\Roaming\Kodi\addons\script.kodi.hue.ambilight-master\default.py", line 141, in start_autodiscover
                                                recv_data, addr = client_socket.recvfrom(2048)
                                            timeout: timed out
                                            -->End of Python script error report<--
```

**Comment by chrisk2305** [comment]
I am having the same issue on openelec. Is this project still alive? Any feedback would be greatly appreciated! Thanks, Christian

**Comment by xuron** [comment]
Hi, I had a similar problem while playing around with different forks of this. (had to reset the settings). 
what worked for me: 
 - restart kodi
 - restart hue bridge 
 - do auto configuration of the addon. 
maybe try koying version: https://github.com/koying/script.kodi.hue.ambilight/tree/master
