### ISSUE TITLE
New Brigde - connection ok but error while playing movie

### ISSUE THREAD

**Issue by jschoorl** [michaelrcarroll/script.kodi.hue.ambilight#6]
I have the new philps hue starterset with the new bulbs and the bridge 2.0 and the new lightstrips plus. In kodi Isengard I can make an automatic connection with the bridge. 

While playing a movie I got an error and the comment to look into the log. Into the log: 

21:58:22 T:4630904832  NOTICE: [plugin.video.kodipopcorntime] Now playing torrent...
21:58:22 T:4612239360   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: set_light2() takes exactly 4 arguments (5 given)
                                            Traceback (most recent call last):
                                              File "/Users/Jurgen/Library/Application Support/Kodi/addons/script.kodi.hue.ambilight-develop/default.py", line 587, in <module>
                                                run()
                                              File "/Users/Jurgen/Library/Application Support/Kodi/addons/script.kodi.hue.ambilight-develop/default.py", line 456, in run
                                                fade_light_hsv(hue.light[0], hsvRatios[0])
                                              File "/Users/Jurgen/Library/Application Support/Kodi/addons/script.kodi.hue.ambilight-develop/default.py", line 475, in fade_light_hsv
                                                light.set_light2(h, s, v, duration)
                                            TypeError: set_light2() takes exactly 4 arguments (5 given)
                                            -->End of Python script error report<--

Thanks for the good work !

**Comment by michaelrcarroll** [comment]
Does this occur when youre not using the ```develop``` branch?

There's a good chance I broke some stuff in there that wasn't ready for primetime, but just want to double check.

**Comment by jschoorl** [comment]
This behaviour is in the developer branche, in the 0.7 I could not make an automatic connection which was the reason to give the developer branche a try.

Met vriendelijke groet,

Jurgen Schoorlemmer

**Comment by michaelrcarroll** [comment]
Hi @jschoorl. Can you please try the [0.7.2](https://github.com/michaelrcarroll/script.kodi.hue.ambilight/releases/tag/0.7.2) release and post a logfile (see [Debugging](https://github.com/michaelrcarroll/script.kodi.hue.ambilight#debugging) section of the readme).

FYI: I've now made some changes to the auto discover functions in 0.7.2, but otherwise nothing was different from 0.7.x and the ```develop``` branch when you tested.

**Comment by jschoorl** [comment]
Hello Michael,

Going to test tomorrow.

Met vriendelijke groet,

Jurgen Schoorlemmer

**Comment by jschoorl** [comment]
Hello Michael,

 

On my imac as wel on windows I get on kodi 15.1 the errorcode

 

“ Add-on hasn’t got the right file structure”. Hopes that this helps.

 

Regards jurgen

 

Van: Michael Carroll [mailto:notifications@github.com] 
Verzonden: maandag 2 november 2015 07:45
Aan: michaelrcarroll/script.kodi.hue.ambilight <script.kodi.hue.ambilight@noreply.github.com>
CC: jschoorl <jurgen@thuy.nl>
Onderwerp: Re: [script.kodi.hue.ambilight] New Brigde - connection ok but error while playing movie (#6)

 

Hi @jschoorl <https://github.com/jschoorl> . Can you please try the 0.7.2 <https://github.com/michaelrcarroll/script.kodi.hue.ambilight/releases/tag/0.7.2>  release and post a logfile (see Debugging <https://github.com/michaelrcarroll/script.kodi.hue.ambilight#debugging>  section of the readme).

FYI: I've now made some changes to the auto discover functions in 0.7.2, but otherwise nothing was different from 0.7.x and the develop branch when you tested.

**Comment by michaelrcarroll** [comment]
Oops! Just saw that the .zip I created was strange. Try the "Source Code (zip)" link: https://github.com/michaelrcarroll/script.kodi.hue.ambilight/archive/0.7.2.zip

**Comment by jschoorl** [comment]
Installation worked, I am not sure about autodiscovery – didn’t see a connection. Attached the log

 

Van: Michael Carroll [mailto:notifications@github.com] 
Verzonden: dinsdag 3 november 2015 23:07
Aan: michaelrcarroll/script.kodi.hue.ambilight <script.kodi.hue.ambilight@noreply.github.com>
CC: jschoorl <jurgen@thuy.nl>
Onderwerp: Re: [script.kodi.hue.ambilight] New Brigde - connection ok but error while playing movie (#6)

 

Oops! Just saw that the .zip I created was strange. Try the "Source Code (zip)" link: https://github.com/michaelrcarroll/script.kodi.hue.ambilight/archive/0.7.2.zip

**Comment by michaelrcarroll** [comment]
Looks like you emailed in the comment. Attachments only work from the Github website. A link to the log on xbmclogs.com would also work.

**Comment by jschoorl** [comment]
See http://xbmclogs.com/pcy003w8t
